apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  # Deployment specs
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        # Image specs
      - name: db
        image: danverh/db-sample:{{ .Values.imageVersion }}
        ports:
        - containerPort: 3306 # for mariadb
        # Probes
        #livenessProbe:
        #  tcpSocket:
        #    port: 5432
        #  initialDelaySeconds: 10
        # ENV variables
        envFrom:
        - secretRef:
            name: db-secret
        # Pull policy
        imagePullPolicy: Always
        volumeMounts:
          - name: azure
            mountPath: /var/lib/mysql  #/var/lib/postgresql/data
      volumes:
        - name: azure
          persistentVolumeClaim:
            claimName: database-pvc

