apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: app
spec:
{{ if eq .Values.replicas 1.0 }}
  minAvailable: 1
{{ else }}
  minAvailable: {{ sub .Values.replicas 1.0 }}
{{ end }}
  selector:
    matchLabels:
      app: backend