apiVersion: v1
kind: Service
metadata:
  name: backend-lb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: 8080
  type: LoadBalancer