apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob
  namespace: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure volumeid is unique for every identical storage blob container in the cluster
    # character `#` and `/` are reserved for internal use and cannot be used in volumehandle
    volumeHandle: {{ .Values.resourceGroup }}#{{ .Values.storageAccount }}#{{ .Values.containerName }}
    volumeAttributes:
      resourceGroup: "{{ .Values.resourceGroup }}"
      storageAccount: "{{ .Values.storageAccount }}"
      containerName: "{{ .Values.containerName }}"
      protocol: nfs