kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-app-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: sample-app-pv
  storageClassName: azureblob-nfs-premium