kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-app-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: sample-app-pv
  storageClassName: azureblob-nfs-premium