apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: stage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "azuredisk-custom-storageclass"
  resources:
    requests:
      storage: 1Gi