apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: app
  labels:
    app: db
spec:
  # Deployment specs
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        # Image specs
      - name: db
        image: danverh/db-sample:latest
        ports:
        - containerPort: 5432
        # Probes
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
        # ENV variables
        envFrom:
        - secretRef:
            name: db-secret
        # Pull policy
        imagePullPolicy: Always