apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  # Deployment specs
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        # Image specs
      - name: backend
        image: danverh/go-sample:latest
        ports:
        - containerPort: 8080
        # Resources
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "10Mi"
            cpu: "10m"
        # Probes
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        # Pull Policy
        imagePullPolicy: Always