apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress2
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    #nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: backend-lb
                port:
                  number: 80