apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  # Deployment specs
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        # Image specs
      - name: frontend
        image: danverh/react-sample:{{ .Values.containers.imageVersion }}
        ports:
        - containerPort: 80
        # Resources
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "10Mi"
            cpu: "10m"
        # Probes
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        # Pull Policy
        imagePullPolicy: Always