apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
  type: LoadBalancer