name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    branches: [ "main" ]
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Build
    - uses: actions/checkout@v3
      working-directory: ./frontend
      run: docker image build --tag danverh/react-sample:latest .
    
    - name: Docker Login
    - uses: docker/login-action@v2.2.0
      with:
        username: $DOCKER_USER
        password: $DOCKER_PASSWORD
        logout: true

    - name: Docker Push
      uses: ./
      working-directory: ./frontend
      run: docker image push danverh/react-sample:latest
